# Generated by Django 5.0.6 on 2025-07-22 14:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('자산', '자산'), ('부채', '부채'), ('순자산', '순자산'), ('수익', '수익'), ('비용', '비용')], default='자산', max_length=10, verbose_name='계정 타입')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='항목명')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='날짜')),
                ('item', models.CharField(max_length=100, verbose_name='아이템')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='메모')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='금액')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='account.account', verbose_name='대변 계정')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debits', to='account.account', verbose_name='차변 계정')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
