# Generated by Django 5.0.6 on 2025-07-23 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='프리셋 이름')),
                ('preset_type', models.CharField(choices=[('FIXED', '고정항목'), ('FREQUENT', '자주입력')], max_length=10, verbose_name='프리셋 타입')),
                ('item', models.CharField(max_length=100, verbose_name='아이템')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='금액 (자주입력은 비워둘 수 있음)')),
                ('day_of_month', models.IntegerField(blank=True, null=True, verbose_name='고정 일자 (예: 25)')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_presets', to='account.account', verbose_name='대변 계정')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_presets', to='account.account', verbose_name='차변 계정')),
            ],
        ),
    ]
