# Generated by Django 5.0.6 on 2026-04-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_transaction_options_account_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='investment_principal',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='투자 원금 (수동)'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_investment',
            field=models.BooleanField(default=False, verbose_name='투자 계좌 여부'),
        ),
    ]
