# Generated by Django 5.0.6 on 2025-08-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('FIXED', '고정'), ('VARIABLE', '유동'), ('SAVING', '저축'), ('GENERAL', '일반')], default='GENERAL', max_length=10, verbose_name='계정 유형'),
        ),
    ]
