# Generated by Django 5.0.6 on 2025-08-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_account_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_repayment',
            field=models.BooleanField(default=False, verbose_name='부채상환 거래'),
        ),
    ]
